name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    name: Ejecutar pruebas unitarias
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Construir el proyecto (opcional)
        run: npm run build
        continue-on-error: true  # Esto no detiene si no existe el script

      - name: Ejecutar pruebas
        run: npm test
        env:
          REACT_APP_API_URL: http://localhost:3000
